backend:
  name: github
  repo: Bloom-Works/gatsby-starter-bloom
  branch: production

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Main Page'
        name: 'index'
        file: 'src/pages/index.content.yml'
        fields:
          - label: Home
            name: home
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
